"""empty message

Revision ID: 36207b1c98dd
Revises: 160b768f42f8
Create Date: 2024-01-22 19:09:29.573432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36207b1c98dd'
down_revision = '160b768f42f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('olleh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('addr', sa.String(length=200), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('course_name', sa.String(length=200), nullable=False),
    sa.Column('distance', sa.String(length=200), nullable=False),
    sa.Column('duration', sa.String(length=200), nullable=False),
    sa.Column('start_point', sa.String(length=200), nullable=False),
    sa.Column('end_pointt', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('olleh')
    # ### end Alembic commands ###
