"""empty message

Revision ID: 5b477be75e88
Revises: e9123e48e9a9
Create Date: 2024-01-20 16:58:28.632923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b477be75e88'
down_revision = 'e9123e48e9a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('select_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.INTEGER(), nullable=False),
    sa.Column('spot1', sa.INTEGER(), nullable=False),
    sa.Column('spot2', sa.INTEGER(), nullable=False),
    sa.Column('food', sa.INTEGER(), nullable=False),
    sa.Column('pet', sa.INTEGER(), nullable=False),
    sa.Column('pool', sa.INTEGER(), nullable=False),
    sa.Column('garden', sa.INTEGER(), nullable=False),
    sa.Column('sea', sa.INTEGER(), nullable=False),
    sa.Column('nocost', sa.INTEGER(), nullable=False),
    sa.Column('bus', sa.INTEGER(), nullable=False),
    sa.Column('police', sa.INTEGER(), nullable=False),
    sa.Column('hospital', sa.INTEGER(), nullable=False),
    sa.Column('bank', sa.INTEGER(), nullable=False),
    sa.Column('mart', sa.INTEGER(), nullable=False),
    sa.Column('gift', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test_tour')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_tour',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tour', sa.VARCHAR(length=200), nullable=False),
    sa.Column('pet', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('select_data')
    # ### end Alembic commands ###
