"""empty message

Revision ID: 6f481efc38e7
Revises: 836af5b573d5
Create Date: 2024-01-19 09:47:32.095403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f481efc38e7'
down_revision = '836af5b573d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_tour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reviewNum', sa.FLOAT(), nullable=False),
    sa.Column('addr', sa.VARCHAR(length=200), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test_tour')
    # ### end Alembic commands ###
