"""empty message

Revision ID: 944a9acf5cb4
Revises: a5990f3503dc
Create Date: 2024-01-21 01:47:51.889045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '944a9acf5cb4'
down_revision = 'a5990f3503dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('reviewNum', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('pension_keyword', sa.String(length=200), nullable=False),
    sa.Column('addr', sa.String(length=200), nullable=False),
    sa.Column('ammen', sa.String(length=200), nullable=False),
    sa.Column('pensionID', sa.Integer(), nullable=False),
    sa.Column('ammen1', sa.String(length=200), nullable=False),
    sa.Column('ammen2', sa.String(length=200), nullable=False),
    sa.Column('ammen3', sa.String(length=200), nullable=False),
    sa.Column('ammen4', sa.String(length=200), nullable=False),
    sa.Column('ammen5', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('select_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.INTEGER(), nullable=False),
    sa.Column('month_str', sa.String(length=200), nullable=False),
    sa.Column('spot1', sa.INTEGER(), nullable=False),
    sa.Column('spot1_str', sa.String(length=200), nullable=False),
    sa.Column('spot2', sa.INTEGER(), nullable=False),
    sa.Column('spot2_str', sa.String(length=200), nullable=False),
    sa.Column('food', sa.INTEGER(), nullable=False),
    sa.Column('food_str', sa.String(length=200), nullable=False),
    sa.Column('pet', sa.INTEGER(), nullable=False),
    sa.Column('pet_str', sa.String(length=200), nullable=False),
    sa.Column('pool', sa.INTEGER(), nullable=False),
    sa.Column('garden', sa.INTEGER(), nullable=False),
    sa.Column('sea', sa.INTEGER(), nullable=False),
    sa.Column('nocost', sa.INTEGER(), nullable=False),
    sa.Column('bus', sa.INTEGER(), nullable=False),
    sa.Column('police', sa.INTEGER(), nullable=False),
    sa.Column('hospital', sa.INTEGER(), nullable=False),
    sa.Column('bank', sa.INTEGER(), nullable=False),
    sa.Column('mart', sa.INTEGER(), nullable=False),
    sa.Column('gift', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('select_data')
    op.drop_table('pension')
    # ### end Alembic commands ###
