"""empty message

Revision ID: 977c0099de85
Revises: e4f079c6e9ee
Create Date: 2024-01-19 17:02:04.770569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977c0099de85'
down_revision = 'e4f079c6e9ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Float(), nullable=False),
    sa.Column('sat', sa.Float(), nullable=False),
    sa.Column('sun', sa.Float(), nullable=False),
    sa.Column('holiday', sa.Float(), nullable=False),
    sa.Column('addr', sa.String(length=200), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('dong', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hospital')
    # ### end Alembic commands ###
