"""empty message

Revision ID: a4cca7dd3201
Revises: 5258bdedc92c
Create Date: 2024-01-19 12:39:13.765666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4cca7dd3201'
down_revision = '5258bdedc92c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pensionID', sa.String(length=200), nullable=False))
        batch_op.create_foreign_key(None, 'pension', ['pensionID'], ['pensionID'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.FLOAT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pensionID')

    # ### end Alembic commands ###
