"""empty message

Revision ID: af9394738c7b
Revises: 6f481efc38e7
Create Date: 2024-01-19 11:41:02.183152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af9394738c7b'
down_revision = '6f481efc38e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pet', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_tour', schema=None) as batch_op:
        batch_op.drop_column('pet')

    # ### end Alembic commands ###
