"""empty message

Revision ID: c25ac2b1eb8f
Revises: 87585821bb21
Create Date: 2024-01-19 13:15:30.251400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c25ac2b1eb8f'
down_revision = '87585821bb21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_data', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'pension', ['pensionID'], ['pensionID'])

    # ### end Alembic commands ###
