"""empty message

Revision ID: e40797f6c099
Revises: af9394738c7b
Create Date: 2024-01-19 11:43:43.215654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40797f6c099'
down_revision = 'af9394738c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_tour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour', sa.String(length=200), nullable=False),
    sa.Column('pet', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_tour')
    # ### end Alembic commands ###
