"""empty message

Revision ID: fbb2700a8d38
Revises: d1a62b2f3c2e
Create Date: 2024-01-21 23:16:17.382314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbb2700a8d38'
down_revision = 'd1a62b2f3c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('addr', sa.String(length=200), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('dong', sa.String(length=200), nullable=True),
    sa.Column('review_rating', sa.Float(), nullable=True),
    sa.Column('review', sa.String(length=200), nullable=True),
    sa.Column('homepage', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gift')
    # ### end Alembic commands ###
